[versions]
agp = "9.4.1"
kotlin = "2.4.20"
mavenPublish = "0.37.0"
compileSdk = "37"
minSdk = "8"
buildTools = "37.0.0"
junit = "4.13.2"
json = "20260814"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
json = { module = "org.json:json", version.ref = "json" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
