plugins {
  id 'com.android.application'
}

android {
  namespace = 'com.orhanobut.sample'
  compileSdk = rootProject.ext.compileSdkVersion
  buildToolsVersion = rootProject.ext.buildToolsVersion
  enableKotlin = false

  defaultConfig {
    applicationId = 'com.orhanobut.sample'
    minSdk = 23
    targetSdk = rootProject.ext.targetSdkVersion
    versionCode = 1
    versionName = '1.0'
  }

  buildFeatures {
    buildConfig = true
  }

  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
}

dependencies {
  implementation project(':logger')
}
